# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hardware_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(411, 452)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(270, 10, 93, 63))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 10, 213, 389))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_APEX = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_APEX.setEnabled(False)
        self.lineEdit_APEX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_APEX.setObjectName("lineEdit_APEX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_APEX)
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_Yokogawa = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Yokogawa.setEnabled(False)
        self.lineEdit_Yokogawa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Yokogawa.setObjectName("lineEdit_Yokogawa")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Yokogawa)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_scope = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_scope.setEnabled(False)
        self.lineEdit_scope.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_scope.setObjectName("lineEdit_scope")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_scope)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_scope_Rigol = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_scope_Rigol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_scope_Rigol.setObjectName("lineEdit_scope_Rigol")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_scope_Rigol)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.label_27)
        self.lineEdit_powermeter_serial_number = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_powermeter_serial_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_powermeter_serial_number.setObjectName("lineEdit_powermeter_serial_number")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_powermeter_serial_number)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.label_24)
        self.lineEdit_laser_Pure_Photonics = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_laser_Pure_Photonics.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_laser_Pure_Photonics.setObjectName("lineEdit_laser_Pure_Photonics")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEdit_laser_Pure_Photonics)
        self.label_31 = QtWidgets.QLabel(self.widget)
        self.label_31.setObjectName("label_31")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.label_31)
        self.lineEdit_piezo_stage = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_piezo_stage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_piezo_stage.setObjectName("lineEdit_piezo_stage")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.lineEdit_piezo_stage)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_LUNA = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_LUNA.setEnabled(False)
        self.lineEdit_LUNA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_LUNA.setObjectName("lineEdit_LUNA")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.lineEdit_LUNA)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_28.setText(_translate("Dialog", "APEX"))
        self.lineEdit_APEX.setText(_translate("Dialog", "10.2.60.25"))
        self.label_30.setText(_translate("Dialog", "Yokogawa"))
        self.lineEdit_Yokogawa.setText(_translate("Dialog", "10.2.60.60"))
        self.label_26.setText(_translate("Dialog", "Scope"))
        self.lineEdit_scope.setText(_translate("Dialog", "10.2.60.176"))
        self.label_25.setText(_translate("Dialog", "Scope Rigol"))
        self.lineEdit_scope_Rigol.setText(_translate("Dialog", "10.2.60.132"))
        self.label_27.setText(_translate("Dialog", "Powermeter serial number"))
        self.lineEdit_powermeter_serial_number.setText(_translate("Dialog", "P0015055"))
        self.label_24.setText(_translate("Dialog", "Laser Pure Photonics"))
        self.lineEdit_laser_Pure_Photonics.setText(_translate("Dialog", "COM4"))
        self.label_31.setText(_translate("Dialog", "Piezo stage"))
        self.lineEdit_piezo_stage.setText(_translate("Dialog", "COM5"))
        self.label_29.setText(_translate("Dialog", "LUNA"))
        self.lineEdit_LUNA.setText(_translate("Dialog", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
